/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gdr;

/**
 *
 * @author danie
 */
public class GameSchermataFinale extends javax.swing.JPanel {
public void setRisultato(String messaggio) {
    lbl_Messaggio.setText(messaggio);
}
    /**
     * Creates new form schermataFinale
     */
    public GameSchermataFinale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Messaggio = new javax.swing.JLabel();

        setLayout(null);

        lbl_Messaggio.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_Messaggio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Messaggio.setText("...");
        add(lbl_Messaggio);
        lbl_Messaggio.setBounds(80, 120, 250, 70);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_Messaggio;
    // End of variables declaration//GEN-END:variables
}
