package gdr;

import java.awt.CardLayout;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author danie
 */
public class GamePanel extends javax.swing.JPanel {
  private CardLayout cardLayout;
    private Grafica grafica; // JFrame principale
    private GameSchermataFinale schermataFinale; // pannello finale
    /**
     * Creates new form GamePanel
     */
    private JTextArea textArea;
    public GamePanel() {
        initComponents();
        textArea = (JTextArea) txt_areaTestoConsole.getViewport().getView();
        textArea.setEditable(false);       // sola lettura
        textArea.setLineWrap(true);        // va a capo automaticamente
        textArea.setWrapStyleWord(true);   // va a capo sulle parole
        
    }
    private void mostraSchermataFinale(String messaggio) {
        schermataFinale.setRisultato(messaggio);
        cardLayout.show(grafica.getContentPane(), "finale");
    }
    void controlloAndamentoPartita(){
        if(GameManager.andamentoPartita().equals("dead")){
            
        }
        else if(GameManager.andamentoPartita().equals("inefficente")){
            
        }
        else if(GameManager.andamentoPartita().equals("malFunzionante")){
            
        }
        
    }
    public void aggiornaDati() {
        Character c = GameManager.getCharScelto();

        this.lbl_hardnessValue.setText(Integer.toString(c.getHardness()));
        this.lbl_IneffValue.setText(Integer.toString(c.getInefficenza()));
        this.lbl_malFunzValue.setText(Integer.toString(c.getMalFunzionamentoStrumento()));
        this.lbl_annotazioneValue.setText(Integer.toString(c.getnAnnotazioni()));
        this.lbl_gadgetValue.setText(Integer.toString(c.getnGadget()));
        this.lbl_personaggio.setText(c.getTypeCharc());
        this.lbl_nturno.setText(Integer.toString(GameManager.getTurno()));
        this.textArea.setText(GameManager.unisciTextDaLista(GameManager.getListaEventixConsole()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_turnoText = new javax.swing.JLabel();
        lbl_nturno = new javax.swing.JLabel();
        lbl_personaggio = new javax.swing.JLabel();
        lbl_hardnessText = new javax.swing.JLabel();
        lbl_malfunzionamentoText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_suona = new javax.swing.JButton();
        lbl_IneffValue = new javax.swing.JLabel();
        lbl_hardnessValue = new javax.swing.JLabel();
        lbl_malFunzValue = new javax.swing.JLabel();
        lbl_gadgetText = new javax.swing.JLabel();
        lbl_annotazioneValue = new javax.swing.JLabel();
        lbl_annotazioniText = new javax.swing.JLabel();
        lbl_gadgetValue = new javax.swing.JLabel();
        btn_annotazioni = new javax.swing.JButton();
        btn_gadget = new javax.swing.JButton();
        txt_areaTestoConsole = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_salvaCsv = new javax.swing.JToggleButton();
        btn_CaricaCSV = new javax.swing.JButton();
        btn_CaricaSer = new javax.swing.JButton();
        btn_salvaSer1 = new javax.swing.JButton();

        setLayout(null);

        lbl_turnoText.setText("Turno:");
        add(lbl_turnoText);
        lbl_turnoText.setBounds(60, 30, 40, 16);

        lbl_nturno.setText("0");
        add(lbl_nturno);
        lbl_nturno.setBounds(100, 30, 37, 16);

        lbl_personaggio.setText("...");
        add(lbl_personaggio);
        lbl_personaggio.setBounds(20, 140, 80, 16);

        lbl_hardnessText.setText("HARDNESS:");
        add(lbl_hardnessText);
        lbl_hardnessText.setBounds(20, 210, 100, 16);

        lbl_malfunzionamentoText.setText("MALFUNZIONAMENTO STRUMENTO:");
        add(lbl_malfunzionamentoText);
        lbl_malfunzionamentoText.setBounds(20, 260, 200, 16);

        jLabel1.setText("INEFFICENZA:");
        add(jLabel1);
        jLabel1.setBounds(20, 320, 110, 16);

        btn_suona.setText("SUONA");
        btn_suona.setToolTipText("");
        btn_suona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suonaActionPerformed(evt);
            }
        });
        add(btn_suona);
        btn_suona.setBounds(430, 50, 120, 23);

        lbl_IneffValue.setText("0");
        add(lbl_IneffValue);
        lbl_IneffValue.setBounds(20, 340, 60, 16);

        lbl_hardnessValue.setText("100");
        add(lbl_hardnessValue);
        lbl_hardnessValue.setBounds(20, 230, 70, 16);

        lbl_malFunzValue.setText("0");
        add(lbl_malFunzValue);
        lbl_malFunzValue.setBounds(20, 280, 50, 16);

        lbl_gadgetText.setText("Gadget:");
        add(lbl_gadgetText);
        lbl_gadgetText.setBounds(270, 270, 50, 16);

        lbl_annotazioneValue.setText("0");
        add(lbl_annotazioneValue);
        lbl_annotazioneValue.setBounds(360, 350, 50, 16);

        lbl_annotazioniText.setText("Annotazioni:");
        add(lbl_annotazioniText);
        lbl_annotazioniText.setBounds(270, 350, 70, 20);

        lbl_gadgetValue.setText("0");
        add(lbl_gadgetValue);
        lbl_gadgetValue.setBounds(360, 270, 50, 16);

        btn_annotazioni.setText("USA ANNOTAZIONE");
        btn_annotazioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annotazioniActionPerformed(evt);
            }
        });
        add(btn_annotazioni);
        btn_annotazioni.setBounds(270, 370, 150, 23);

        btn_gadget.setText("USA GADGET");
        btn_gadget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gadgetActionPerformed(evt);
            }
        });
        add(btn_gadget);
        btn_gadget.setBounds(270, 290, 140, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        txt_areaTestoConsole.setViewportView(jTextArea1);

        add(txt_areaTestoConsole);
        txt_areaTestoConsole.setBounds(430, 100, 330, 410);

        btn_salvaCsv.setText("Salva CSV");
        btn_salvaCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvaCsvActionPerformed(evt);
            }
        });
        add(btn_salvaCsv);
        btn_salvaCsv.setBounds(800, 110, 110, 23);

        btn_CaricaCSV.setText("Carica CSV");
        btn_CaricaCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CaricaCSVActionPerformed(evt);
            }
        });
        add(btn_CaricaCSV);
        btn_CaricaCSV.setBounds(800, 140, 110, 23);

        btn_CaricaSer.setText("Carica Serializ");
        btn_CaricaSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CaricaSerActionPerformed(evt);
            }
        });
        add(btn_CaricaSer);
        btn_CaricaSer.setBounds(800, 270, 120, 23);

        btn_salvaSer1.setText("Salva Serializ");
        btn_salvaSer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvaSer1ActionPerformed(evt);
            }
        });
        add(btn_salvaSer1);
        btn_salvaSer1.setBounds(800, 240, 120, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_suonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suonaActionPerformed
        Evento e = GameManager.generaEvento();
        GameManager.svolgiEvento(e);
        Salvataggio.addEventToList(EventManager.text4Event(e));
        GameManager.setTurno(GameManager.getTurno() - 1);
        aggiornaDati();
    }//GEN-LAST:event_btn_suonaActionPerformed

    private void btn_annotazioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annotazioniActionPerformed
        GameManager.getCharScelto().setInefficenza(GameManager.getCharScelto().getInefficenza()-10);
    }//GEN-LAST:event_btn_annotazioniActionPerformed

    private void btn_gadgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gadgetActionPerformed
      GameManager.getCharScelto().setMalFunzionamentoStrumento(GameManager.getCharScelto().getMalFunzionamentoStrumento()-10);  
    }//GEN-LAST:event_btn_gadgetActionPerformed

    private void btn_salvaCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvaCsvActionPerformed
        FileManager.salvaCSV(GameManager.getCharScelto(), GameManager.getListaEventixConsole());
    }//GEN-LAST:event_btn_salvaCsvActionPerformed

    private void btn_salvaSer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvaSer1ActionPerformed
        FileManager.salvaSerializzazione(GameManager.getCharScelto(), GameManager.getListaEventixConsole());
    }//GEN-LAST:event_btn_salvaSer1ActionPerformed

    private void btn_CaricaCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CaricaCSVActionPerformed
        FileManager.letturaCSV();
        aggiornaDati();
    }//GEN-LAST:event_btn_CaricaCSVActionPerformed

    private void btn_CaricaSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CaricaSerActionPerformed
        FileManager.letturaSerializzazione();
        aggiornaDati();
    }//GEN-LAST:event_btn_CaricaSerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CaricaCSV;
    private javax.swing.JButton btn_CaricaSer;
    private javax.swing.JButton btn_annotazioni;
    private javax.swing.JButton btn_gadget;
    private javax.swing.JToggleButton btn_salvaCsv;
    private javax.swing.JButton btn_salvaSer1;
    private javax.swing.JButton btn_suona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_IneffValue;
    private javax.swing.JLabel lbl_annotazioneValue;
    private javax.swing.JLabel lbl_annotazioniText;
    private javax.swing.JLabel lbl_gadgetText;
    private javax.swing.JLabel lbl_gadgetValue;
    private javax.swing.JLabel lbl_hardnessText;
    private javax.swing.JLabel lbl_hardnessValue;
    private javax.swing.JLabel lbl_malFunzValue;
    private javax.swing.JLabel lbl_malfunzionamentoText;
    private javax.swing.JLabel lbl_nturno;
    private javax.swing.JLabel lbl_personaggio;
    private javax.swing.JLabel lbl_turnoText;
    private javax.swing.JScrollPane txt_areaTestoConsole;
    // End of variables declaration//GEN-END:variables
}
